### PR TITLE
Update to IdentityToolkit-V1 API and add more example use cases

### PR DESCRIPTION
**Pull request by troyhen**

### CODE REVIEW

**Comment by samtstern** [comment]
@troyhen wow thank you for submitting this!  I am happy to merge it if you are willing to sign the CLA.

**Comment by troyhen** [comment]
@samtstern  What is the CLA and how do I sign it?

**Comment by samtstern** [comment]
@troyhen it's explained fully in this command:
https://github.com/FirebaseExtended/auth-without-play-services/pull/3#issuecomment-565683788

But basically visit https://cla.developers.google.com/ ... this is something you only have to do once ever and any future contributions to Google owned repos won't have this blocker.  Thanks again for the work!

**Comment by troyhen** [comment]
@googlebot I signed it!

**Comment by samtstern** [comment]
@troyhen don't worry about the last CLA thing, it's confused because your git commits are not signed with the same email as your GitHub account.  I did an override.  Thank you for signing it!

**Comment by troyhen** [comment]
Can you tell me how to sign my GIT commits? I guess I didn't know that was a thing.

**Comment by samtstern** [comment]
@troyhen thank you again for submitting this PR!

If you run this command you can see the email used to sign your commits:
```
$ git config --get user.email
samstern@google.com
```

My guess is that on your system that's not the same email you use to sign in with GitHub.  You can change it either globally on a per-repo basis using these commands:
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git

**Pull request merged**
